/**
 * Generated by @openapi-codegen
 *
 * @version 1.0
 */
export type News = {
  url?: string | null;
  title?: string | null;
  summary?: string | null;
  imageUrl?: string | null;
  imageData?: string | null;
};
