/**
 * Generated by @openapi-codegen
 *
 * @version 1.0.0
 */
import * as reactQuery from "@tanstack/react-query";
import {
  type BackendContext,
  useBackendContext,
  queryKeyFn,
} from "./backendContext";
import { deepMerge } from "./backendUtils";
import type * as Fetcher from "./backendFetcher";
import { backendFetch } from "./backendFetcher";
import type * as Schemas from "./backendSchemas";

type QueryFnOptions = {
  signal?: AbortController["signal"];
};

export type GetNewsError = Fetcher.ErrorWrapper<undefined>;

export type GetNewsRequestBody = null | Schemas.GetNewsRequest;

export type GetNewsVariables = {
  body?: GetNewsRequestBody;
} & BackendContext["fetcherOptions"];

export const fetchGetNews = (
  variables: GetNewsVariables,
  signal?: AbortSignal,
) =>
  backendFetch<
    Schemas.GetNewsResponse,
    GetNewsError,
    GetNewsRequestBody,
    {},
    {},
    {}
  >({ url: "/api/News", method: "post", ...variables, signal });

export const useGetNews = (
  options?: Omit<
    reactQuery.UseMutationOptions<
      Schemas.GetNewsResponse,
      GetNewsError,
      GetNewsVariables
    >,
    "mutationFn"
  >,
) => {
  const { fetcherOptions } = useBackendContext();
  return reactQuery.useMutation<
    Schemas.GetNewsResponse,
    GetNewsError,
    GetNewsVariables
  >({
    mutationFn: (variables: GetNewsVariables) =>
      fetchGetNews(deepMerge(fetcherOptions, variables)),
    ...options,
  });
};

export type QueryOperation = {
  path: string;
  operationId: never;
  variables: unknown | reactQuery.SkipToken;
};
