/**
 * Generated by @openapi-codegen
 *
 * @version 1.0
 */
export type GetNewsRequest = {
  /**
   * 'true' if latest news shall be returned, 'false' otherwise. Default is 'true'
   */
  isLatest?: boolean | null;
};

export type News = {
  url?: string | null;
  title?: string | null;
  summary?: string | null;
  imageUrl?: string | null;
  imageData?: string | null;
};
