/**
 * Generated by @openapi-codegen
 *
 * @version 1.0.0
 */
export type GetNewsRequest = {
  /**
   * 'true' if latest news shall be returned, 'false' otherwise. Default is 'false'
   */
  isLatest?: boolean | null;
} | null;

export type GetNewsResponse = {
  items?: News[];
};

export type News = {
  url?: string;
  title?: string;
  summary?: string;
  imageUrl?: string;
  imageData?: string;
};
